name: Build and update image

on:
  push:
    branches:
      - main
    tags:
      - "*"

  workflow_dispatch: #allow manual trigger to workflow

jobs:
  test_on_pr:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Check smart contract
        run: |
          yarn 
          npx hardhat test