name: PR tests

on:
  pull_request:
    branches:
      - main

jobs:
  test_on_pr:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Check smart contract
        run: |
          cd $GITHUB_WORKSPACE
          yarn 
          npx hardhat test
