name: PR tests

on:
  pull_request:
    branches:
      - master

jobs:
  test_on_pr:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Check smart contract
        run: |
          yarn 
          npx hardhat test
