name: PR tests

on:
  pull_request:
    branches:
      - master

jobs:
  test_on_pr:
    name: Test on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Check smart contract
        run: |
          yarn 
          npx hardhat test
